### ISSUE TITLE
Dependency on GTK2

### ISSUE THREAD

**Issue by woodsb02** [riggs-/xfce4-bsdcpufreq-plugin#1]
The new Xfce 4.14 release has updated all code to move from GTK2 to GTK3, however this plugin still depends on GTK2.

**Comment by ephemeralriggs** [comment]
It's on my list. Since FreeBSD's xfce4-panel package depends on gtk2 by default, it's not a show stopper yet.

**Comment by woodsb02** [comment]
Thanks.

Please also be aware of the current lock contention problem 😂 - the xfce4-panel package only depends on GTK2 so that it can support panel plugins that require GTK2 (haven’t been upgraded to use GTK3). This was discussed at the link below.
https://reviews.freebsd.org/D21919

**Comment by woodsb02** [comment]
Just a heads up that it looks like the priority on this has increased.

The latest release of Xfce4-panel 4.15 has dropped support for Gtk2 plugins:
https://mail.xfce.org/pipermail/xfce-announce/2019-October/000794.html

**Comment by ephemeralriggs** [comment]
Port to gtk3 is done in a093f8620026b80990c45e7e3905d80452ae7f09.

**Comment by woodsb02** [comment]
Awesome works - thanks!
